Replace Circle CI in CONTRIBUTING.MD
vapor/queues pull request #90
Opened 2020-10-21 18:44 UTC by siemensikkema

2020-10-21 18:47 UTC, jdmcd requested changes
Just one quick comment!

2020-10-21 18:47 UTC, jdmcd commented on .github/CONTRIBUTING.MD
>  - [@mcdappdev](https://github.com/mcdappdev)
Can you update this to my new username? Jdmcd please! I would do it but I'm on mobile, thanks!

2020-10-23 08:53 UTC, siemensikkema commented on .github/CONTRIBUTING.MD
>  - [@mcdappdev](https://github.com/mcdappdev)
```suggestion
- [@mcdappdev](https://github.com/jdmcd)
```

2020-10-23 08:53 UTC, siemensikkema commented on .github/CONTRIBUTING.MD
> +See the [Vapor maintainers doc](https://github.com/vapor/vapor/blob/master/Docs/maintainers.md) for more information.
```suggestion
See the [Vapor maintainers doc](https://github.com/vapor/vapor/blob/master/.github/maintainers.md) for more information. 
```

2020-10-26 11:10 UTC, MrLotU approved these changes

2020-10-26 11:26 UTC, jdmcd approved these changes

2020-10-26 11:26 UTC, merged